name: oro_irrigation_new
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.1.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  mqtt_client: ^10.0.0
  shared_preferences: ^2.1.0
  intl_phone_number_input: ^0.7.3+1
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^22.2.12
  data_table_2: ^2.5.8
  popover: ^0.2.8+2
  side_sheet: ^1.0.4
  provider: ^6.0.5
  loading_indicator: ^3.1.0
  linked_scroll_controller: ^0.2.0
  flutter_time_picker_spinner: ^2.0.0
  numberpicker: ^2.1.2
  rxdart: ^0.27.0
  image_picker: ^1.0.4
  webview_flutter: ^2.0.10
  intl: ^0.18.1
  reorderable_grid_view: ^2.2.8
  fl_chart: ^0.65.0
  search_page: ^2.3.0
  uuid: ^4.2.2
  chat_bubbles: ^1.5.0
  sleek_circular_slider: ^2.0.1
  excel: ^4.0.2
  audioplayers: ^5.2.1
  flutter_svg: ^0.22.0
  snapping_sheet: ^3.1.0
  flutter_date_range_picker: ^0.0.14
  syncfusion_flutter_datepicker: ^22.2.12
  material_design_icons_flutter: ^7.0.7296
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  google_maps_flutter_web: ^0.5.7
  syncfusion_flutter_gauges: ^22.2.12
  syncfusion_flutter_xlsio: ^22.2.12
  universal_html: ^2.2.4
  syncfusion_flutter_calendar: ^22.2.12
  timezone: ^0.9.2
  flutter_gemini: ^2.0.4
  lottie: ^2.7.0
  flutter_markdown: ^0.7.3
  google_generative_ai: ^0.4.3
  calendar_view: ^1.2.0
  device_info_plus: ^10.1.0
  archive: ^3.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/otp_illustrator.png
     - assets/images/mqttError.png
     - assets/images/login_illustrator.png
     - assets/images/user_thumbnail.png
     - assets/images/no_data.jpg
     - assets/images/irrigation_pump.png
     - assets/images/source_pump.png
     - assets/images/main_valve.png
     - assets/images/method.svg
     - assets/images/time_quantity.svg
     - assets/images/moisture_condition.svg
     - assets/images/level_condition.svg
     - assets/images/pre_post_method.svg
     - assets/images/pre_value.svg
     - assets/images/post_value.svg
     - assets/images/valve.png
     - assets/images/central_filtration.png
     - assets/images/central_dosing.png
     - assets/images/moisture_sensor.png
     - assets/images/level_sensor.png
     - assets/images/fert_chanel.png
     - assets/images/oro_switch.png
     - assets/images/oro_gem.png
     - assets/images/oro_sense.png
     - assets/images/oro_rtu.png
     - assets/images/channel_img.png
     - assets/images/river.png
     - assets/images/co2.png
     - assets/images/humidity.png
     - assets/images/ldrSensor.png
     - assets/images/leafWetness.png
     - assets/images/lux.png
     - assets/images/moisture.png
     - assets/images/rainGauge.png
     - assets/images/soilTemperature.png
     - assets/images/temperature.png
     - assets/images/windDirection.png
     - assets/images/windSpeed.png
     - assets/images/newConfig.png
     - assets/images/sendToServer.png
     - assets/images/success.png
     - assets/images/analog_sensor.png
     - assets/images/booster_pump.png
     - assets/images/central_fertilizer_site.png
     - assets/images/central_filtration_site.png
     - assets/images/agitator.png
     - assets/images/injector.png
     - assets/images/filter.png
     - assets/images/downstream_valve.png
     - assets/images/fan.png
     - assets/images/fan_green.png
     - assets/images/fan_orange.png
     - assets/images/fan_red.png
     - assets/images/fogger.png
     - assets/images/fogger_green.png
     - assets/images/fogger_orange.png
     - assets/images/fogger_red.png
     - assets/images/selector.png
     - assets/images/selector_g.png
     - assets/images/selector_y.png
     - assets/images/selector_r.png
     - assets/images/water_meter.png
     - assets/images/fertilizer_meter.png
     - assets/images/pressure_switch.png
     - assets/images/pressure_sensor.png
     - assets/images/differential_pressure_sensor.png
     - assets/images/ec_sensor.png
     - assets/images/ph_sensor.png
     - assets/images/temperature_sensor.png
     - assets/images/soil_temperature_sensor.png
     - assets/images/wind_direction_sensor.png
     - assets/images/wind_speed_sensor.png
     - assets/images/lux_sensor.png
     - assets/images/ldr_sensor.png
     - assets/images/humidity_sensor.png
     - assets/images/leaf_wetness_sensor.png
     - assets/images/rain_gauge_sensor.png
     - assets/images/contact.png
     - assets/images/irrigation_line.png
     - assets/images/weather_station.png
     - assets/images/condition.png
     - assets/images/valve_group.png
     - assets/images/virtual_water_meter.png
     - assets/images/programs.png
     - assets/images/radiation_sets.png
     - assets/images/fertilization_sets.png
     - assets/images/filter_sets.png
     - assets/images/water_source.png
     - assets/GifFile/c2.gif
     - assets/images/w04.png
     - assets/images/w19.gif
     - assets/images/w51.gif
     - assets/images/w52.gif
     - assets/images/db_valve.png
     - assets/images/dp_prs_sensor.png
     - assets/images/weather_view.jpg
     - assets/images/irrigation_image.jpg
     - assets/GifFile/water_drop_animation.gif
     - assets/images/relief_valve.png
     - assets/images/channel.png
     - assets/images/company_logo.png
     - assets/images/niagara_logo.png
     - assets/images/w08.png
     - assets/images/w09.png
     - assets/images/w10.png
     - assets/images/w12.png
     - assets/images/w13.png
     - assets/images/w14.png
     - assets/images/sunset.png
     - assets/images/sunrise.png
     - assets/images/dew-point.png
     - assets/images/downpour-rain.png
     - assets/images/RainRate.png
     - assets/images/Rel.Press.png
     - assets/images/bgcolor.png
     - assets/images/windy.png
     - assets/images/uv.png
     - assets/images/hoursClock.png
     - assets/images/24hoursClock.png
     - assets/images/minsClock.png
     - assets/audios/button_click_sound.mp3
     - assets/audios/audio_off.mp3
     - assets/images/clock_needle.png
     - assets/images/line.png
     - assets/images/default_icon.svg
     - assets/images/default.svg
     - assets/SVGPicture/login_left_picture.svg
     - assets/images/tableOptionSelected.svg
     - assets/SVGPicture/oro_logo.svg
     - assets/images/login_top_corner.png
     - assets/images/oro_logo_white.png
     - assets/SVGPicture/irrigation_line_icon.svg
     - assets/SVGPicture/irrigation_line_icon_svg.svg
     - assets/GifFile/dp_filter_g.gif
     - assets/GifFile/dp_filter_y.gif
     - assets/GifFile/dp_filter_r.gif
     - assets/GifFile/dp_filter_1_g.gif
     - assets/GifFile/dp_filter_2_g.gif
     - assets/GifFile/dp_filter_3_g.gif
     - assets/GifFile/dp_filter_1_y.gif
     - assets/GifFile/dp_filter_2_y.gif
     - assets/GifFile/dp_filter_3_y.gif
     - assets/GifFile/dp_filter_1_r.gif
     - assets/GifFile/dp_filter_2_r.gif
     - assets/GifFile/dp_filter_3_r.gif
     - assets/images/dp_filter.png
     - assets/images/dp_filter_1.png
     - assets/images/dp_filter_2.png
     - assets/images/dp_filter_3.png
     - assets/GifFile/dp_irr_pump_y.gif
     - assets/GifFile/dp_irr_pump_1_y.gif
     - assets/GifFile/dp_irr_pump_2_y.gif
     - assets/GifFile/dp_irr_pump_3_y.gif
     - assets/GifFile/dp_irr_pump_r.gif
     - assets/GifFile/dp_irr_pump_1_r.gif
     - assets/GifFile/dp_irr_pump_2_r.gif
     - assets/GifFile/dp_irr_pump_3_r.gif
     - assets/GifFile/dp_irr_pump_g.gif
     - assets/GifFile/dp_irr_pump_1_g.gif
     - assets/GifFile/dp_irr_pump_3_g.gif
     - assets/images/dp_irr_pump.png
     - assets/images/dp_irr_pump_1.png
     - assets/images/dp_irr_pump_2.png
     - assets/images/dp_irr_pump_3.png
     - assets/images/dp_fert_first_tank.png
     - assets/images/dp_fert_center_tank.png
     - assets/images/dp_fert_channel_center.png
     - assets/images/dp_fert_channel_center_g.png
     - assets/images/dp_fert_channel_center_y.png
     - assets/images/dp_fert_channel_center_r.png
     - assets/images/dp_fert_channel_last.png
     - assets/images/dp_fert_channel_last_g.png
     - assets/images/dp_fert_channel_last_y.png
     - assets/images/dp_fert_channel_last_r.png
     - assets/images/dp_agitator_right.png
     - assets/images/dp_fert_last_tank.png
     - assets/images/dp_fert_channel_last.png
     - assets/images/dp_fert_channel_last_g.png
     - assets/images/dp_fert_channel_last_y.png
     - assets/images/dp_fert_channel_last_r.png
     - assets/images/dp_fert_nrv.png
     - assets/images/dp_fert_booster_pump.png
     - assets/images/dp_fert_booster_pump_y.png
     - assets/images/dp_fert_booster_pump_r.png
     - assets/GifFile/dp_fert_booster_pump_g.gif
     - assets/images/dp_flowmeter.png
     - assets/images/valve_gray.png
     - assets/images/valve_green.png
     - assets/images/valve_red.png
     - assets/images/valve_orange.png
     - assets/images/dp_main_valve_closed.png
     - assets/images/dp_main_valve_not_open.png
     - assets/images/dp_main_valve_open.png
     - assets/images/dp_main_valve_wait.png
     - assets/images/dp_fert_last_tank1.png
     - assets/images/dp_fert_first_tank1.png
     - assets/SVGPicture/default.svg
     - assets/GifFile/dp_irr_pump_g.gif
     - assets/images/dp_irr_pump_y.png
     - assets/images/dp_irr_pump_r.png
     - assets/images/joining_line.png
     - assets/images/dp_sump.png
     - assets/images/dp_filter_g.png
     - assets/images/dp_filter_r.png
     - assets/images/dp_filter_y.png
     - assets/images/dp_agitator_right_g.png
     - assets/images/dp_agitator_right_y.png
     - assets/images/dp_agitator_right_r.png
     - assets/images/dp_fert_channel_first_aj.png
     - assets/images/dp_fert_channel_first_aj_g.png
     - assets/images/dp_fert_channel_first_aj_y.png
     - assets/images/dp_fert_channel_first_aj_r.png
     - assets/images/dp_fert_channel_center_aj.png
     - assets/images/dp_fert_channel_center_aj_g.png
     - assets/images/dp_fert_channel_center_aj_y.png
     - assets/images/dp_fert_channel_center_aj_r.png
     - assets/images/dp_fert_channel_last_aj.png
     - assets/images/dp_fert_channel_last_aj_g.png
     - assets/images/dp_fert_channel_last_aj_y.png
     - assets/images/dp_fert_channel_last_aj_r.png
     - assets/images/dp_sump_src.png
     - assets/images/dp_agitator_gray.png
     - assets/images/dp_agitator_green.png
     - assets/images/dp_agitator_yellow.png
     - assets/images/dp_agitator_red.png
     - assets/GifFile/motor_off_new.gif
     - assets/GifFile/motor_on_new.gif
     - assets/GifFile/motor_ondelay_new.gif
     - assets/images/dp_fert_vertical_pipe.png
     - assets/images/dp_fert_vertical_pipe.png
     - assets/images/dl_valve.png
     - assets/images/dl_main_valve.png
     - assets/images/dl_source_pump.png
     - assets/images/dl_irrigation_pump.png
     - assets/images/dl_analog_sensor.png
     - assets/images/dl_level_sensor.png
     - assets/images/dl_booster_pump.png
     - assets/images/dl_central_fertilizer_site.png
     - assets/images/dl_central_filtration_site.png
     - assets/images/dl_agitator.png
     - assets/images/dl_filter.png
     - assets/images/dl_co2.png
     - assets/images/dl_condition.png
     - assets/images/dl_contact.png
     - assets/images/dl_differential_pressure_sensor.png
     - assets/images/dl_downstream_valve.png
     - assets/images/dl_ec_sensor.png
     - assets/images/dl_fan.png
     - assets/images/dl_fertilizer_meter.png
     - assets/images/dl_filter_sets.png
     - assets/images/dl_fogger.png
     - assets/images/dl_injector.png
     - assets/images/dl_irrigation_pump.png
     - assets/images/dl_ph_sensor.png
     - assets/images/dl_pressure_sensor.png
     - assets/images/dl_pressure_switch.png
     - assets/images/dl_programs.png
     - assets/images/dl_rain_gauge_sensor.png
     - assets/images/dl_selector.png
     - assets/images/dl_soil_temperature_sensor.png
     - assets/images/dl_valve_group.png
     - assets/images/dl_virtual_water_meter.png
     - assets/images/dl_water_meter.png
     - assets/images/dl_water_source.png
     - assets/images/dl_irrigation_line.png
     - assets/images/dl_moisture_sensor.png
     - assets/images/dl_temperature_sensor.png
     - assets/images/dl_fertilization_sets.png
     - assets/images/dl_float.png
     - assets/images/dl_tank_float.png
     - assets/images/dl_moisture_condition.png
     - assets/images/dl_power_supply.png
     - assets/images/dl_power_supply.png
     - assets/images/dl_level_condition.png
     - assets/images/dl_common_pressure_sensor.png
     - assets/images/dl_common_pressure_switch.png
     - assets/images/dl_humidity_sensor.png
     - assets/weather/airpressure.png
     - assets/weather/airtemperature.png
     - assets/weather/co2sensor.png
     - assets/weather/humidity.png
     - assets/weather/leafwetness.png
     - assets/weather/luxsensor.png
     - assets/weather/rainfall.png
     - assets/weather/soilmoisture.png
     - assets/weather/soilmoisture-1.png
     - assets/weather/temperature3.png
     - assets/weather/winddirection.png
     - assets/weather/windspeed.png
     - assets/weather/oro_gem.png
     - assets/weather/markergray.png
     - assets/weather/markerorange.png
     - assets/weather/markerred.png
     - assets/weather/booster_pump.png
     - assets/GifFile/water_drop_ani.gif
     - assets/SVGPicture/login_top_pic.svg
     - assets/weather/markergreen.png
     - assets/weather/markeryellow.png
     - assets/weather/compass.png
     - assets/images/sump.svg
     - assets/weatherIcons2/CO-2.png
     - assets/weatherIcons2/humidity.png
     - assets/weatherIcons2/LDR.png
     - assets/weatherIcons2/leafWetness.png
     - assets/weatherIcons2/Lux.png
     - assets/weatherIcons2/pressure.png
     - assets/weatherIcons2/rainFall.png
     - assets/weatherIcons2/SoilMoisture.png
     - assets/weatherIcons2/SoilTemp .png
     - assets/weatherIcons2/sunrise.gif
     - assets/weatherIcons2/temperature.png
     - assets/weatherIcons2/WindDirection.png
     - assets/weatherIcons2/WindSpeed.png
     - assets/weatherIcons2/WindSpeedColor.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
